#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

gruvYellow="#D79921"
gray2="#5A5A5A"
bspc config active_border_color $gruvYellow
bspc config focused_border_color $gruvYellow
bspc config normal_border_color $gray2

bspc rule -a Screenkey manage=off
